// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: securetest.proto

package distsys.recruitmentday.securetest;

public final class SecureTestProto {
  private SecureTestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VideoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:securetest.Video)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool camera = 1;</code>
     * @return The camera.
     */
    boolean getCamera();
  }
  /**
   * Protobuf type {@code securetest.Video}
   */
  public static final class Video extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:securetest.Video)
      VideoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Video.newBuilder() to construct.
    private Video(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Video() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Video();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Video(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              camera_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_Video_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_Video_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              distsys.recruitmentday.securetest.SecureTestProto.Video.class, distsys.recruitmentday.securetest.SecureTestProto.Video.Builder.class);
    }

    public static final int CAMERA_FIELD_NUMBER = 1;
    private boolean camera_;
    /**
     * <code>bool camera = 1;</code>
     * @return The camera.
     */
    @java.lang.Override
    public boolean getCamera() {
      return camera_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (camera_ != false) {
        output.writeBool(1, camera_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (camera_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, camera_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof distsys.recruitmentday.securetest.SecureTestProto.Video)) {
        return super.equals(obj);
      }
      distsys.recruitmentday.securetest.SecureTestProto.Video other = (distsys.recruitmentday.securetest.SecureTestProto.Video) obj;

      if (getCamera()
          != other.getCamera()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CAMERA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCamera());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.Video parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(distsys.recruitmentday.securetest.SecureTestProto.Video prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code securetest.Video}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:securetest.Video)
        distsys.recruitmentday.securetest.SecureTestProto.VideoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_Video_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_Video_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                distsys.recruitmentday.securetest.SecureTestProto.Video.class, distsys.recruitmentday.securetest.SecureTestProto.Video.Builder.class);
      }

      // Construct using distsys.recruitmentday.securetest.SecureTestProto.Video.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        camera_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_Video_descriptor;
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.Video getDefaultInstanceForType() {
        return distsys.recruitmentday.securetest.SecureTestProto.Video.getDefaultInstance();
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.Video build() {
        distsys.recruitmentday.securetest.SecureTestProto.Video result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.Video buildPartial() {
        distsys.recruitmentday.securetest.SecureTestProto.Video result = new distsys.recruitmentday.securetest.SecureTestProto.Video(this);
        result.camera_ = camera_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof distsys.recruitmentday.securetest.SecureTestProto.Video) {
          return mergeFrom((distsys.recruitmentday.securetest.SecureTestProto.Video)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(distsys.recruitmentday.securetest.SecureTestProto.Video other) {
        if (other == distsys.recruitmentday.securetest.SecureTestProto.Video.getDefaultInstance()) return this;
        if (other.getCamera() != false) {
          setCamera(other.getCamera());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        distsys.recruitmentday.securetest.SecureTestProto.Video parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (distsys.recruitmentday.securetest.SecureTestProto.Video) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean camera_ ;
      /**
       * <code>bool camera = 1;</code>
       * @return The camera.
       */
      @java.lang.Override
      public boolean getCamera() {
        return camera_;
      }
      /**
       * <code>bool camera = 1;</code>
       * @param value The camera to set.
       * @return This builder for chaining.
       */
      public Builder setCamera(boolean value) {
        
        camera_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool camera = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCamera() {
        
        camera_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:securetest.Video)
    }

    // @@protoc_insertion_point(class_scope:securetest.Video)
    private static final distsys.recruitmentday.securetest.SecureTestProto.Video DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new distsys.recruitmentday.securetest.SecureTestProto.Video();
    }

    public static distsys.recruitmentday.securetest.SecureTestProto.Video getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Video>
        PARSER = new com.google.protobuf.AbstractParser<Video>() {
      @java.lang.Override
      public Video parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Video(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Video> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Video> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public distsys.recruitmentday.securetest.SecureTestProto.Video getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MonitoringResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:securetest.MonitoringResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string warning = 1;</code>
     * @return The warning.
     */
    java.lang.String getWarning();
    /**
     * <code>string warning = 1;</code>
     * @return The bytes for warning.
     */
    com.google.protobuf.ByteString
        getWarningBytes();
  }
  /**
   * Protobuf type {@code securetest.MonitoringResponse}
   */
  public static final class MonitoringResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:securetest.MonitoringResponse)
      MonitoringResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MonitoringResponse.newBuilder() to construct.
    private MonitoringResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonitoringResponse() {
      warning_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MonitoringResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MonitoringResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              warning_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_MonitoringResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_MonitoringResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse.class, distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse.Builder.class);
    }

    public static final int WARNING_FIELD_NUMBER = 1;
    private volatile java.lang.Object warning_;
    /**
     * <code>string warning = 1;</code>
     * @return The warning.
     */
    @java.lang.Override
    public java.lang.String getWarning() {
      java.lang.Object ref = warning_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        warning_ = s;
        return s;
      }
    }
    /**
     * <code>string warning = 1;</code>
     * @return The bytes for warning.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWarningBytes() {
      java.lang.Object ref = warning_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        warning_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(warning_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, warning_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(warning_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, warning_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse)) {
        return super.equals(obj);
      }
      distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse other = (distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse) obj;

      if (!getWarning()
          .equals(other.getWarning())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WARNING_FIELD_NUMBER;
      hash = (53 * hash) + getWarning().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code securetest.MonitoringResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:securetest.MonitoringResponse)
        distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_MonitoringResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_MonitoringResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse.class, distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse.Builder.class);
      }

      // Construct using distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        warning_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_MonitoringResponse_descriptor;
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse getDefaultInstanceForType() {
        return distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse.getDefaultInstance();
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse build() {
        distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse buildPartial() {
        distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse result = new distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse(this);
        result.warning_ = warning_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse) {
          return mergeFrom((distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse other) {
        if (other == distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse.getDefaultInstance()) return this;
        if (!other.getWarning().isEmpty()) {
          warning_ = other.warning_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object warning_ = "";
      /**
       * <code>string warning = 1;</code>
       * @return The warning.
       */
      public java.lang.String getWarning() {
        java.lang.Object ref = warning_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          warning_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string warning = 1;</code>
       * @return The bytes for warning.
       */
      public com.google.protobuf.ByteString
          getWarningBytes() {
        java.lang.Object ref = warning_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          warning_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string warning = 1;</code>
       * @param value The warning to set.
       * @return This builder for chaining.
       */
      public Builder setWarning(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        warning_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string warning = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWarning() {
        
        warning_ = getDefaultInstance().getWarning();
        onChanged();
        return this;
      }
      /**
       * <code>string warning = 1;</code>
       * @param value The bytes for warning to set.
       * @return This builder for chaining.
       */
      public Builder setWarningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        warning_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:securetest.MonitoringResponse)
    }

    // @@protoc_insertion_point(class_scope:securetest.MonitoringResponse)
    private static final distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse();
    }

    public static distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonitoringResponse>
        PARSER = new com.google.protobuf.AbstractParser<MonitoringResponse>() {
      @java.lang.Override
      public MonitoringResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MonitoringResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonitoringResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MonitoringResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public distsys.recruitmentday.securetest.SecureTestProto.MonitoringResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestAnswerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:securetest.TestAnswer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string answer = 1;</code>
     * @return The answer.
     */
    java.lang.String getAnswer();
    /**
     * <code>string answer = 1;</code>
     * @return The bytes for answer.
     */
    com.google.protobuf.ByteString
        getAnswerBytes();
  }
  /**
   * Protobuf type {@code securetest.TestAnswer}
   */
  public static final class TestAnswer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:securetest.TestAnswer)
      TestAnswerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestAnswer.newBuilder() to construct.
    private TestAnswer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestAnswer() {
      answer_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestAnswer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestAnswer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              answer_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestAnswer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestAnswer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              distsys.recruitmentday.securetest.SecureTestProto.TestAnswer.class, distsys.recruitmentday.securetest.SecureTestProto.TestAnswer.Builder.class);
    }

    public static final int ANSWER_FIELD_NUMBER = 1;
    private volatile java.lang.Object answer_;
    /**
     * <code>string answer = 1;</code>
     * @return The answer.
     */
    @java.lang.Override
    public java.lang.String getAnswer() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        answer_ = s;
        return s;
      }
    }
    /**
     * <code>string answer = 1;</code>
     * @return The bytes for answer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAnswerBytes() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(answer_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, answer_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(answer_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, answer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof distsys.recruitmentday.securetest.SecureTestProto.TestAnswer)) {
        return super.equals(obj);
      }
      distsys.recruitmentday.securetest.SecureTestProto.TestAnswer other = (distsys.recruitmentday.securetest.SecureTestProto.TestAnswer) obj;

      if (!getAnswer()
          .equals(other.getAnswer())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getAnswer().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(distsys.recruitmentday.securetest.SecureTestProto.TestAnswer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code securetest.TestAnswer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:securetest.TestAnswer)
        distsys.recruitmentday.securetest.SecureTestProto.TestAnswerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestAnswer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestAnswer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                distsys.recruitmentday.securetest.SecureTestProto.TestAnswer.class, distsys.recruitmentday.securetest.SecureTestProto.TestAnswer.Builder.class);
      }

      // Construct using distsys.recruitmentday.securetest.SecureTestProto.TestAnswer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        answer_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestAnswer_descriptor;
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.TestAnswer getDefaultInstanceForType() {
        return distsys.recruitmentday.securetest.SecureTestProto.TestAnswer.getDefaultInstance();
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.TestAnswer build() {
        distsys.recruitmentday.securetest.SecureTestProto.TestAnswer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.TestAnswer buildPartial() {
        distsys.recruitmentday.securetest.SecureTestProto.TestAnswer result = new distsys.recruitmentday.securetest.SecureTestProto.TestAnswer(this);
        result.answer_ = answer_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof distsys.recruitmentday.securetest.SecureTestProto.TestAnswer) {
          return mergeFrom((distsys.recruitmentday.securetest.SecureTestProto.TestAnswer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(distsys.recruitmentday.securetest.SecureTestProto.TestAnswer other) {
        if (other == distsys.recruitmentday.securetest.SecureTestProto.TestAnswer.getDefaultInstance()) return this;
        if (!other.getAnswer().isEmpty()) {
          answer_ = other.answer_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        distsys.recruitmentday.securetest.SecureTestProto.TestAnswer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (distsys.recruitmentday.securetest.SecureTestProto.TestAnswer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object answer_ = "";
      /**
       * <code>string answer = 1;</code>
       * @return The answer.
       */
      public java.lang.String getAnswer() {
        java.lang.Object ref = answer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          answer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string answer = 1;</code>
       * @return The bytes for answer.
       */
      public com.google.protobuf.ByteString
          getAnswerBytes() {
        java.lang.Object ref = answer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string answer = 1;</code>
       * @param value The answer to set.
       * @return This builder for chaining.
       */
      public Builder setAnswer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        answer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string answer = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnswer() {
        
        answer_ = getDefaultInstance().getAnswer();
        onChanged();
        return this;
      }
      /**
       * <code>string answer = 1;</code>
       * @param value The bytes for answer to set.
       * @return This builder for chaining.
       */
      public Builder setAnswerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        answer_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:securetest.TestAnswer)
    }

    // @@protoc_insertion_point(class_scope:securetest.TestAnswer)
    private static final distsys.recruitmentday.securetest.SecureTestProto.TestAnswer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new distsys.recruitmentday.securetest.SecureTestProto.TestAnswer();
    }

    public static distsys.recruitmentday.securetest.SecureTestProto.TestAnswer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestAnswer>
        PARSER = new com.google.protobuf.AbstractParser<TestAnswer>() {
      @java.lang.Override
      public TestAnswer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestAnswer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestAnswer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestAnswer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public distsys.recruitmentday.securetest.SecureTestProto.TestAnswer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:securetest.TestResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>repeated string answers = 2;</code>
     * @return A list containing the answers.
     */
    java.util.List<java.lang.String>
        getAnswersList();
    /**
     * <code>repeated string answers = 2;</code>
     * @return The count of answers.
     */
    int getAnswersCount();
    /**
     * <code>repeated string answers = 2;</code>
     * @param index The index of the element to return.
     * @return The answers at the given index.
     */
    java.lang.String getAnswers(int index);
    /**
     * <code>repeated string answers = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the answers at the given index.
     */
    com.google.protobuf.ByteString
        getAnswersBytes(int index);
  }
  /**
   * Protobuf type {@code securetest.TestResult}
   */
  public static final class TestResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:securetest.TestResult)
      TestResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestResult.newBuilder() to construct.
    private TestResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestResult() {
      message_ = "";
      answers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                answers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              answers_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          answers_ = answers_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              distsys.recruitmentday.securetest.SecureTestProto.TestResult.class, distsys.recruitmentday.securetest.SecureTestProto.TestResult.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWERS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList answers_;
    /**
     * <code>repeated string answers = 2;</code>
     * @return A list containing the answers.
     */
    public com.google.protobuf.ProtocolStringList
        getAnswersList() {
      return answers_;
    }
    /**
     * <code>repeated string answers = 2;</code>
     * @return The count of answers.
     */
    public int getAnswersCount() {
      return answers_.size();
    }
    /**
     * <code>repeated string answers = 2;</code>
     * @param index The index of the element to return.
     * @return The answers at the given index.
     */
    public java.lang.String getAnswers(int index) {
      return answers_.get(index);
    }
    /**
     * <code>repeated string answers = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the answers at the given index.
     */
    public com.google.protobuf.ByteString
        getAnswersBytes(int index) {
      return answers_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      for (int i = 0; i < answers_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, answers_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < answers_.size(); i++) {
          dataSize += computeStringSizeNoTag(answers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAnswersList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof distsys.recruitmentday.securetest.SecureTestProto.TestResult)) {
        return super.equals(obj);
      }
      distsys.recruitmentday.securetest.SecureTestProto.TestResult other = (distsys.recruitmentday.securetest.SecureTestProto.TestResult) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getAnswersList()
          .equals(other.getAnswersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (getAnswersCount() > 0) {
        hash = (37 * hash) + ANSWERS_FIELD_NUMBER;
        hash = (53 * hash) + getAnswersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(distsys.recruitmentday.securetest.SecureTestProto.TestResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code securetest.TestResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:securetest.TestResult)
        distsys.recruitmentday.securetest.SecureTestProto.TestResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                distsys.recruitmentday.securetest.SecureTestProto.TestResult.class, distsys.recruitmentday.securetest.SecureTestProto.TestResult.Builder.class);
      }

      // Construct using distsys.recruitmentday.securetest.SecureTestProto.TestResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = "";

        answers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return distsys.recruitmentday.securetest.SecureTestProto.internal_static_securetest_TestResult_descriptor;
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.TestResult getDefaultInstanceForType() {
        return distsys.recruitmentday.securetest.SecureTestProto.TestResult.getDefaultInstance();
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.TestResult build() {
        distsys.recruitmentday.securetest.SecureTestProto.TestResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public distsys.recruitmentday.securetest.SecureTestProto.TestResult buildPartial() {
        distsys.recruitmentday.securetest.SecureTestProto.TestResult result = new distsys.recruitmentday.securetest.SecureTestProto.TestResult(this);
        int from_bitField0_ = bitField0_;
        result.message_ = message_;
        if (((bitField0_ & 0x00000001) != 0)) {
          answers_ = answers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.answers_ = answers_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof distsys.recruitmentday.securetest.SecureTestProto.TestResult) {
          return mergeFrom((distsys.recruitmentday.securetest.SecureTestProto.TestResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(distsys.recruitmentday.securetest.SecureTestProto.TestResult other) {
        if (other == distsys.recruitmentday.securetest.SecureTestProto.TestResult.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.answers_.isEmpty()) {
          if (answers_.isEmpty()) {
            answers_ = other.answers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnswersIsMutable();
            answers_.addAll(other.answers_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        distsys.recruitmentday.securetest.SecureTestProto.TestResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (distsys.recruitmentday.securetest.SecureTestProto.TestResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList answers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAnswersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          answers_ = new com.google.protobuf.LazyStringArrayList(answers_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string answers = 2;</code>
       * @return A list containing the answers.
       */
      public com.google.protobuf.ProtocolStringList
          getAnswersList() {
        return answers_.getUnmodifiableView();
      }
      /**
       * <code>repeated string answers = 2;</code>
       * @return The count of answers.
       */
      public int getAnswersCount() {
        return answers_.size();
      }
      /**
       * <code>repeated string answers = 2;</code>
       * @param index The index of the element to return.
       * @return The answers at the given index.
       */
      public java.lang.String getAnswers(int index) {
        return answers_.get(index);
      }
      /**
       * <code>repeated string answers = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the answers at the given index.
       */
      public com.google.protobuf.ByteString
          getAnswersBytes(int index) {
        return answers_.getByteString(index);
      }
      /**
       * <code>repeated string answers = 2;</code>
       * @param index The index to set the value at.
       * @param value The answers to set.
       * @return This builder for chaining.
       */
      public Builder setAnswers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAnswersIsMutable();
        answers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string answers = 2;</code>
       * @param value The answers to add.
       * @return This builder for chaining.
       */
      public Builder addAnswers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAnswersIsMutable();
        answers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string answers = 2;</code>
       * @param values The answers to add.
       * @return This builder for chaining.
       */
      public Builder addAllAnswers(
          java.lang.Iterable<java.lang.String> values) {
        ensureAnswersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, answers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string answers = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnswers() {
        answers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string answers = 2;</code>
       * @param value The bytes of the answers to add.
       * @return This builder for chaining.
       */
      public Builder addAnswersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAnswersIsMutable();
        answers_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:securetest.TestResult)
    }

    // @@protoc_insertion_point(class_scope:securetest.TestResult)
    private static final distsys.recruitmentday.securetest.SecureTestProto.TestResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new distsys.recruitmentday.securetest.SecureTestProto.TestResult();
    }

    public static distsys.recruitmentday.securetest.SecureTestProto.TestResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestResult>
        PARSER = new com.google.protobuf.AbstractParser<TestResult>() {
      @java.lang.Override
      public TestResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public distsys.recruitmentday.securetest.SecureTestProto.TestResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securetest_Video_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securetest_Video_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securetest_MonitoringResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securetest_MonitoringResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securetest_TestAnswer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securetest_TestAnswer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securetest_TestResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_securetest_TestResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020securetest.proto\022\nsecuretest\"\027\n\005Video\022" +
      "\016\n\006camera\030\001 \001(\010\"%\n\022MonitoringResponse\022\017\n" +
      "\007warning\030\001 \001(\t\"\034\n\nTestAnswer\022\016\n\006answer\030\001" +
      " \001(\t\".\n\nTestResult\022\017\n\007message\030\001 \001(\t\022\017\n\007a" +
      "nswers\030\002 \003(\t2\247\001\n\021SecureTestService\022K\n\022Mo" +
      "nitorTestSession\022\021.securetest.Video\032\036.se" +
      "curetest.MonitoringResponse(\0010\001\022E\n\021Submi" +
      "tTestAnswers\022\026.securetest.TestAnswer\032\026.s" +
      "ecuretest.TestResult(\001B4\n!distsys.recrui" +
      "tmentday.securetestB\017SecureTestProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_securetest_Video_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_securetest_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securetest_Video_descriptor,
        new java.lang.String[] { "Camera", });
    internal_static_securetest_MonitoringResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_securetest_MonitoringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securetest_MonitoringResponse_descriptor,
        new java.lang.String[] { "Warning", });
    internal_static_securetest_TestAnswer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_securetest_TestAnswer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securetest_TestAnswer_descriptor,
        new java.lang.String[] { "Answer", });
    internal_static_securetest_TestResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_securetest_TestResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_securetest_TestResult_descriptor,
        new java.lang.String[] { "Message", "Answers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
