// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: turnstile.proto

package distsys.recruitmentday.turnstile;

public final class Turnstile {
  private Turnstile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CheckPinRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:turnstile.CheckPinRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 pin = 1;</code>
     * @return The pin.
     */
    int getPin();
  }
  /**
   * Protobuf type {@code turnstile.CheckPinRequest}
   */
  public static final class CheckPinRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:turnstile.CheckPinRequest)
      CheckPinRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckPinRequest.newBuilder() to construct.
    private CheckPinRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckPinRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CheckPinRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckPinRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pin_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest.class, distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest.Builder.class);
    }

    public static final int PIN_FIELD_NUMBER = 1;
    private int pin_;
    /**
     * <code>int32 pin = 1;</code>
     * @return The pin.
     */
    @java.lang.Override
    public int getPin() {
      return pin_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pin_ != 0) {
        output.writeInt32(1, pin_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pin_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest)) {
        return super.equals(obj);
      }
      distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest other = (distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest) obj;

      if (getPin()
          != other.getPin()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PIN_FIELD_NUMBER;
      hash = (53 * hash) + getPin();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code turnstile.CheckPinRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:turnstile.CheckPinRequest)
        distsys.recruitmentday.turnstile.Turnstile.CheckPinRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest.class, distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest.Builder.class);
      }

      // Construct using distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pin_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinRequest_descriptor;
      }

      @java.lang.Override
      public distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest getDefaultInstanceForType() {
        return distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest.getDefaultInstance();
      }

      @java.lang.Override
      public distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest build() {
        distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest buildPartial() {
        distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest result = new distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest(this);
        result.pin_ = pin_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest) {
          return mergeFrom((distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest other) {
        if (other == distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest.getDefaultInstance()) return this;
        if (other.getPin() != 0) {
          setPin(other.getPin());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pin_ ;
      /**
       * <code>int32 pin = 1;</code>
       * @return The pin.
       */
      @java.lang.Override
      public int getPin() {
        return pin_;
      }
      /**
       * <code>int32 pin = 1;</code>
       * @param value The pin to set.
       * @return This builder for chaining.
       */
      public Builder setPin(int value) {
        
        pin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pin = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPin() {
        
        pin_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:turnstile.CheckPinRequest)
    }

    // @@protoc_insertion_point(class_scope:turnstile.CheckPinRequest)
    private static final distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest();
    }

    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckPinRequest>
        PARSER = new com.google.protobuf.AbstractParser<CheckPinRequest>() {
      @java.lang.Override
      public CheckPinRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckPinRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckPinRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckPinRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public distsys.recruitmentday.turnstile.Turnstile.CheckPinRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckPinResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:turnstile.CheckPinResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool access_granted = 1;</code>
     * @return The accessGranted.
     */
    boolean getAccessGranted();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code turnstile.CheckPinResponse}
   */
  public static final class CheckPinResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:turnstile.CheckPinResponse)
      CheckPinResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckPinResponse.newBuilder() to construct.
    private CheckPinResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckPinResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CheckPinResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckPinResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              accessGranted_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse.class, distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse.Builder.class);
    }

    public static final int ACCESS_GRANTED_FIELD_NUMBER = 1;
    private boolean accessGranted_;
    /**
     * <code>bool access_granted = 1;</code>
     * @return The accessGranted.
     */
    @java.lang.Override
    public boolean getAccessGranted() {
      return accessGranted_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (accessGranted_ != false) {
        output.writeBool(1, accessGranted_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (accessGranted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, accessGranted_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse)) {
        return super.equals(obj);
      }
      distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse other = (distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse) obj;

      if (getAccessGranted()
          != other.getAccessGranted()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCESS_GRANTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAccessGranted());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code turnstile.CheckPinResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:turnstile.CheckPinResponse)
        distsys.recruitmentday.turnstile.Turnstile.CheckPinResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse.class, distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse.Builder.class);
      }

      // Construct using distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        accessGranted_ = false;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return distsys.recruitmentday.turnstile.Turnstile.internal_static_turnstile_CheckPinResponse_descriptor;
      }

      @java.lang.Override
      public distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse getDefaultInstanceForType() {
        return distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse.getDefaultInstance();
      }

      @java.lang.Override
      public distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse build() {
        distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse buildPartial() {
        distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse result = new distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse(this);
        result.accessGranted_ = accessGranted_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse) {
          return mergeFrom((distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse other) {
        if (other == distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse.getDefaultInstance()) return this;
        if (other.getAccessGranted() != false) {
          setAccessGranted(other.getAccessGranted());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean accessGranted_ ;
      /**
       * <code>bool access_granted = 1;</code>
       * @return The accessGranted.
       */
      @java.lang.Override
      public boolean getAccessGranted() {
        return accessGranted_;
      }
      /**
       * <code>bool access_granted = 1;</code>
       * @param value The accessGranted to set.
       * @return This builder for chaining.
       */
      public Builder setAccessGranted(boolean value) {
        
        accessGranted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool access_granted = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessGranted() {
        
        accessGranted_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:turnstile.CheckPinResponse)
    }

    // @@protoc_insertion_point(class_scope:turnstile.CheckPinResponse)
    private static final distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse();
    }

    public static distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckPinResponse>
        PARSER = new com.google.protobuf.AbstractParser<CheckPinResponse>() {
      @java.lang.Override
      public CheckPinResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckPinResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckPinResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckPinResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public distsys.recruitmentday.turnstile.Turnstile.CheckPinResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turnstile_CheckPinRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_turnstile_CheckPinRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turnstile_CheckPinResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_turnstile_CheckPinResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017turnstile.proto\022\tturnstile\"\036\n\017CheckPin" +
      "Request\022\013\n\003pin\030\001 \001(\005\";\n\020CheckPinResponse" +
      "\022\026\n\016access_granted\030\001 \001(\010\022\017\n\007message\030\002 \001(" +
      "\t2W\n\020TurnstileService\022C\n\010CheckPin\022\032.turn" +
      "stile.CheckPinRequest\032\033.turnstile.CheckP" +
      "inResponseB-\n distsys.recruitmentday.tur" +
      "nstileB\tTurnstileb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_turnstile_CheckPinRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_turnstile_CheckPinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_turnstile_CheckPinRequest_descriptor,
        new java.lang.String[] { "Pin", });
    internal_static_turnstile_CheckPinResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_turnstile_CheckPinResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_turnstile_CheckPinResponse_descriptor,
        new java.lang.String[] { "AccessGranted", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
